require:
- rubocop-rails
- rubocop-rspec

AllCops:
  Exclude:
    - "bin/*"
    - "db/*"
    - "config/*/*"
    - "Guardfile"
    - "Rakefile"
  DisplayCopNames: true
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"